### ISSUE TITLE
Webfinger when debug=true

### ISSUE THREAD

**Issue by rhaamo** [tsileo/little-boxes#11]
hello,

When using debug with my app, my "federated apps" are using localhost, I've seen that ```check_url``` does have a ```debug``` flag, but webfinger doesn't pass any: https://github.com/tsileo/little-boxes/blob/9943e2b047fc4171c2cf28c543b033b0e855dc78/little_boxes/webfinger.py#L35

Would it be possible to pass a ```debug``` flag to ```webfinger``` to be able to do a lookup when developing ?

**Comment by tsileo** [comment]
Hey,

You're right, the webfinger helper should also have a debug mode.

I will take a look soon,
Thanks!

**Comment by rhaamo** [comment]
Having it on ```get_actor_url``` might be great too in fact.
I use that function to get the actor_url, which I fetch right after to get an user "profile".

**Comment by rhaamo** [comment]
Hi, any news on that ?
