### ISSUE TITLE
README example does not work

### ISSUE THREAD

**Issue by bill-auger** [tsileo/little-boxes#17]
running the "Getting Started" example did not get me very far - upon instantiating a MyBackend object, i got the following error:

```
    def inbox_new(self, as_actor: ap.Person, activity: ap.Activity) -> None:
AttributeError: module 'little_boxes.activitypub' has no attribute 'Activity'
```

after changing 'ap.Activity' to 'ap.BaseActivity', i got this error:

```
    my_backend = MyBackend(db_con)
TypeError: Can't instantiate abstract class MyBackend with abstract methods activity_url, base_url, note_url
```

once i implemented the abstract methods activity_url, base_url, note_url, i got this error:

```
    me = ap.Person({})  # Init an actor
TypeError: __init__() takes 1 positional argument but 2 were given
```

after removing the empty dict from the call to the Person constructor, i got this error:

```
    outbox = ap.Outbox(me)
AttributeError: module 'little_boxes.activitypub' has no attribute 'Outbox'
```

at this point, i can "get started" no further - that 'Outbox' class does not exist in this code-base

i can understand "early development", but after 166 commits, shouldn't the most basic boilerplate functionality work? - isn't an inbox and outbox the primary fundamental core features of activity-pub? - (little_boxes.activitypub has no attribute Inbox either)

am i just confused? - i am not a huge python guy - i can only assume i have done something wrong - can this actually be used today to process activity-pub messages? - i only need the absolute basic activity-pub functionality for a demo

**Comment by tsileo** [comment]
Hi,

The README does need an update, I will try to update it whenever I have time.

You can look at https://github.com/tsileo/microblog.pub for a real-world example.

And yes, it's used to process ActivityPub message, but via microblog.pub, see: https://fediverse.network/microblogpub

Finally, keep in mind little-boxes is a low-level framework, and not something meant to be ready to use out the box. Maybe you should look for a different project.

**Comment by bill-auger** [comment]
i know it not intended to be turn-key solution; but it should do what it
says on the tin, or it should say something different on the tin - i
only need the most basic functionality - im not looking to make a
website - all i really need is a function to which i can pass blobs of
JSON incoming to the web server, to be interpreted as activity-pub
messages, and log them - for now, i dont even need to handle them or
store them, just recognize them incoming and create some bogus ones to
test outgoing

it looks that the 'inbox_new()' and 'post_to_remote_inbox()' methods
were intended to be the inbox and outbox, or somehow intrinsically
related to that functionality; but it is not clear how relation was
intended - for example, if there is not, and was never intended to be an
Outbox class in the 'little_boxes::activitypub' module, then why
would the example code have ever had:

  from little_boxes import activitypub as ap
  outbox = ap.Outbox(me)

likewise, why mention the post() method on a class that was never
intended to exist in the library?

  outbox.post(follow)

why be so explicit, instead or a comment like: "# this is where you
must implement your own Outbox class - the only conclusion to draw from
that, is that this was not intended to be example code to "get you
started"; but pseudo-code illustrating a vague workflow - it appears to
be example code to get you started; but it does not actually get you
anywhere, but a series of error messages that lead to a dead end

if clients need to implement the missing Inbox/Outbox themselves, then
those clearly would not be part of the little-boxes library, as the
example code suggests that they were intended to be - if this was not
intended to be pseudo-code, then the only logical conclusion is that it
is a planned feature; but the library is yet incomplete - thats why im
asking - it looks that this library is missing its primary core feature

your reply comes across as suggesting the library is intentionally
incomplete, just one specialized module in a larger inter-dependent set
of projects; and therefore not intended to be generally useful - isnt
the inbox/outbox abstraction something that would be an essential part
of any activity-pub library? - arent those precisely the 'boxes'
promised in the 'little-boxes' name?
