### ISSUE TITLE
Python 3.6 dependency prevents use on Debian stretch

### ISSUE THREAD

**Issue by khimaros** [tsileo/little-boxes#18]
Would it be possible to update the requirements to require nothing newer than Python version 3.5.3? This would allow microblog.pub and little-boxes to be used on Debian Stretch (stable).

**Comment by tsileo** [comment]
No, it's worth supporting older version to me.
Also, microblog.pub is designed to run with docker-compose/within Docker, which "remove" this issue.

Running microblog.pub with Docker makes everything easier (backup included).

I'm working on the docs and a CLI wizard for microblog.pub to make it easy to get running.

**Comment by khimaros** [comment]
Sounds like you're making a reasonable trade-off in terms of effort. FWIW, I am running microblog.pub in Docker alongside a number of other containers. I've chosen Debian stretch as a base image for my Docker containers as the consistency simplifies certain maintenance tasks for me. Thanks for your reply.

**Comment by tsileo** [comment]
Interesting, so you're using a custom Docker image for every project you're running? I guess you're using a virtualenv then?

Also, running the latest Python allow the project to use (and me to test) new Python features (like type annotations, and I've also started using dataclasses in the codebase, which are Python3.7+ only)

(BTW there's a migration in preparation, in the `drop-celery` branch that will replace Celery and RabbitMQ by [poussetaches](https://github.com/tsileo/poussetaches), it's working well on my 2 instances)
