### ISSUE TITLE
Cannot Handle HTTP 403

### ISSUE THREAD

**Issue by cwt** [tsileo/little-boxes#21]
Recently one of my following friendica server think user-agent sent by microblog/little-boxes is a bot, and then return HTTP 403 which little-boxes backend cannot handle it.

I quick fix it on my running instance by adding 403 to the line `elif resp.status_code in [500, 502, 503]:` in backend.py, but I think it's not a right thing to do.

**Comment by tsileo** [comment]
Hey, any idea why Friendica is blocking the user agent? It seems weird to me that they block "unknown" user agent (unless it's a private instance maybe?)

I will try to take a look at Friendica codebase, and on microblog.pub side, when receiving a 403, except giving up, I don't see what else it can do in this case.

**Comment by cwt** [comment]
I don't know why, may be just only that user put me in black list or something. another following user on the same friendica host do not return 403.

btw, if you think 403 should be handled on the microblog.pub side instead of little-boxes, then please feel free to close this issue.
